version: "3"

services:
  # gitea:
  #   image: gitea/gitea:1.16.3
  #   container_name: gitea
  #   environment:
  #     - USER_UID=1000
  #     - USER_GID=1000
  #   restart: always
  #   volumes:
  #     - ./gitea_data:/data
  #   ports:
  #     - "3800:3000"
  #     - "3222:22"
  jenkins:
    image: 'jenkins/jenkins:lts-jdk11'
    container_name: jenkins
    restart: always
    ports:
      - '8888:8080'
      - '50000:50000'
    volumes:
      - './jenkins_home:/var/jenkins_home'
      - './jenkins_web:/home/web'
    environment:
      - JAVA_OPTS=-Xmx2048m -Djava.awt.headless=true
