version: "3"

services:
  nginx_proxy:
    image: nginx:1.25.2
    hostname: nginx
    container_name: nginx_proxy
    # restart: unless-stopped
    volumes:
      - ./www-data:/var/www # place your files for web here
      - ./nginx-conf:/etc/nginx/conf.d # place provided nginx.conf here
      - ./logs:/var/log/nginx
    ports:
      - 8000:80
