version: '3.8'

services:
  my-sshder:
    image: actspace/my-sshder:0.0.5
    container_name: my-sshder
    # restart: unless-stopped
    environment:
      # first user
      - SSH_USER_1=andersen
      - SSH_GROUP_1=dev
      - SSH_PASS_1=oiceuthn
      
      # second user
      - SSH_USER_2=actspace
      - SSH_GROUP_2=test 
      - SSH_PASS_2=cytu2369
    volumes:
      - ./ssh:/ssh
    ports:
      - '2222:22'