version: '3.8'

volumes:
  my-jenkins-home:

services:

  # GitLab Runner
  GitLab-Runner:
    image: gitlab/gitlab-runner:latest
    container_name: GitLab-Runner
    privileged: true # 允許在docker容器中啓動docker容器
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./GitLab-Runner-Config:/etc/gitlab-runner

  # File Storage (SSH Server)
  file-server:
    image: actspace/my-sshder:0.0.11
    container_name: file-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    ports:
      - '2022:22'

  # node Server (Linux with novnc and node.js<PM2>)
  node-server:
    image: actspace/my-node-server:0.0.5
    container_name: node-server
    restart: unless-stopped
    environment:
      - SSH_USER_1=admin
      - SSH_GROUP_1=admin
      - SSH_PASS_1=oiceuthn
    volumes:
      - ./apps:/apps
      - ./ssh:/ssh
    ports:
      - '2122:22'
      - '3000:3000'

  # Jenkins (use for backup file<git and sql>)
  my-jenkins:
    image: actspace/myjenkins:0.0.1
    container_name: my-jenkins
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 768M
    environment:
      JAVA_OPTS: '-Xms512m -Xmx1024m -Djava.awt.headless=true'
    ports:
      - '8888:8080'
    volumes:
      - my-jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  # MySQL (for backend)
  mysql5.7:
    image: mysql:5.7.43
    container_name: mysql_5.7.43
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1000M
    ports:
      - 13307:3306
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=0000
      - MYSQL_ROOT_PASSWORD=test
      - TZ=Asia/Taipei
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci #設置utf8字符集
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./deploy/sql/:/docker-entrypoint-initdb.d/ # 初始化的腳本，若 ./__data/mysql/ 文件夾存在數據，則不會執行初始化腳本